# Generated by Django 4.2.30 on 2026-05-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=16)),
                ('payload', models.JSONField(help_text='Parsed rows/JSON as received')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'Utility'), ('TRAVEL', 'Travel')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 (fuel)'), ('SCOPE_2', 'Scope 2 (electricity)'), ('SCOPE_3', 'Scope 3 (travel & procurement)')], db_index=True, max_length=16)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('quantity_raw', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('unit_raw', models.CharField(blank=True, max_length=32)),
                ('quantity_normalized', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('unit_normalized', models.CharField(blank=True, max_length=32)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('quality_flags', models.JSONField(default=list, help_text='List of QualityFlag values')),
                ('normalized_payload', models.JSONField(default=dict, help_text='Unified schema snapshot')),
                ('source_row_index', models.PositiveIntegerField(default=0, help_text='Index in raw payload rows')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128)),
                ('review_notes', models.TextField(blank=True)),
                ('edited_flag', models.BooleanField(default=False)),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_rows', to='records.rawdatarecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AirportDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_iata', models.CharField(db_index=True, max_length=3)),
                ('to_iata', models.CharField(db_index=True, max_length=3)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'unique_together': {('from_iata', 'to_iata')},
            },
        ),
        migrations.CreateModel(
            name='PlantCodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_code', models.CharField(db_index=True, max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_mappings', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'sap_code')},
            },
        ),
    ]
